### ISSUE TITLE
Deleting element_templates folder

### ISSUE THREAD

**Issue by nomadaisy** [votinginfoproject/csv-templates#3]
I would like to delete the element_templates folder from the data_templates folder. It contains older files that already exist in db_templates, the main source for template headers.

**Comment by jungshadow** [comment]
Sounds good. The old element templates were just a one-to-one representation of the VIP XML elements. It was a convenient way to translate CSVs into the XML, but ended up making the database queries a bit onerous. Destroy when ready.
